server:
  port: 8080
spring:
  datasource:
    name: gh
    url: jdbc:mysql://127.0.0.1:3306?characterEncoding=utf8&useSSL=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true
mybatis:
  mapper-locations: classpath:mapping/*.xml
logging:
  level:
    root: INFO
    com.yamibuy.central.po.dao: DEBUG
  file: /home/log/po.log

